### ISSUE TITLE
Fix musl libc dns problems with glibc?

### ISSUE THREAD

**Issue by maklemenz** [frol/docker-alpine-glibc#1]
Hi, can you Fix the [DNS-problems of alpine](http://gliderlabs.viewdocs.io/docker-alpine/caveats/) using glibc?

Since musl libc ignores SEARCH and DOMAIN in /etc/resolv.conf and uses parallel querying of name servers it can't be used in environments that require that (like kubernetes).

I don't know how this can be done but it looks like you are more familiar with the differences of musl libc and glibc.

**Comment by frol** [comment]
Using glibc and binaries linked against glibc will workaround the issue with musl libc by avoiding musl libc completely. However, this is a bit pointless to use Alpine with glibc as you almost completely give up on package management as Alpine's packages are linked against musl libc.

Here is the proof (I use `/usr/bin/ping` from my host OS, Arch Linux, which is glibc based):

```bash
$ docker run -it --rm --dns 8.8.8.8 --dns-search google.com -v /usr/bin/ping:/usr/bin/ping -v /usr/lib/libcap.so.2:/usr/lib/libcap.so.2 -v /usr/lib/libattr.so.1
:/usr/lib/libattr.so.1 frolvlad/alpine-glibc sh
/ # /usr/bin/ping photos
PING photos.google.com (110.164.6.187) 56(84) bytes of data.
64 bytes from mx-ll-110.164.6-187.static.3bb.co.th (110.164.6.187): icmp_seq=1 ttl=56 time=18.0 ms
64 bytes from mx-ll-110.164.6-187.static.3bb.co.th (110.164.6.187): icmp_seq=2 ttl=56 time=17.7 ms
64 bytes from mx-ll-110.164.6-187.static.3bb.co.th (110.164.6.187): icmp_seq=3 ttl=56 time=18.5 ms
^C
--- photos.google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 17.723/18.130/18.591/0.372 ms
```

However, using Alpine's version of `ping` (in `/bin/ping`) in the same session, it reveals the issue with musl libc:

```bash
/ # /bin/ping photos
ping: bad address 'photos'
```
