### ISSUE TITLE
no version information available 

### ISSUE THREAD

**Issue by kingmayko** [frol/docker-alpine-glibc#13]
Hi, i have the question with the image

I add below in dockerfile 
RUN apk --update add --no-cache  libstdc++

but will appear  /usr/lib/libstdc++.so.6: no version information available 
 when execute binary file.

how could i solve this problem.

**Comment by frol** [comment]
If you use glibc, most of the time you also need glibc-based libraries. You may try to get libstdc++ package from Arch Linux, see my [`alpine-mono` Dockerfile](https://github.com/frol/docker-alpine-mono/blob/master/Dockerfile).

*Disclaimer: This whole thing with glibc on Alpine is just a hack, I am OK with this hack, it works fine for me, but you should expect that it is not as user-friendly as `apt-get install`.*

**Comment by kingmayko** [comment]
thanks.
