### ISSUE TITLE
symbol not found

### ISSUE THREAD

**Issue by colinlabs** [frol/docker-alpine-glibc#14]
hi guys, I try using this image to install python `cx_Oracle` library, and get this error:
```shell
/usr/lib/instantclient_12_1 # ldd libclntsh.so.12.1
	ldd (0x561095877000)
	libmql1.so => /usr/lib/instantclient_12_1/libmql1.so (0x7fbb66577000)
	libipc1.so => /usr/lib/instantclient_12_1/libipc1.so (0x7fbb661f9000)
	libnnz12.so => /usr/lib/instantclient_12_1/libnnz12.so (0x7fbb65aef000)
	libons.so => /usr/lib/instantclient_12_1/libons.so (0x7fbb658aa000)
	libdl.so.2 => ldd (0x561095877000)
	libm.so.6 => ldd (0x561095877000)
	libpthread.so.0 => ldd (0x561095877000)
Error loading shared library libnsl.so.1: No such file or directory (needed by libclntsh.so.12.1)
	librt.so.1 => ldd (0x561095877000)
	libc.so.6 => ldd (0x561095877000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7fbb65685000)
	libaio.so.1 => /usr/lib/libaio.so.1 (0x7fbb65483000)
	libclntshcore.so.12.1 => /usr/lib/instantclient_12_1/libclntshcore.so.12.1 (0x7fbb64f11000)
Error loading shared library libnsl.so.1: No such file or directory (needed by /usr/lib/instantclient_12_1/libclntshcore.so.12.1)
Error relocating /usr/lib/instantclient_12_1/libipc1.so: __cmsg_nxthdr: symbol not found
Error relocating libclntsh.so.12.1: canonicalize_file_name: symbol not found
Error relocating libclntsh.so.12.1: getcontext: symbol not found
Error relocating libclntsh.so.12.1: bindresvport: symbol not found
Error relocating libclntsh.so.12.1: __finite: symbol not found
```

**Comment by frol** [comment]
I haven't tried cx_Oracle, so there is no experience whether it is going to work at all, but here are some pointers:

1. The `ldd` output is not accurate as it is `ldd` from Alpine, meaning that it expects musl binaries. You may just use `LD_TRACE_LOADED_OBJECTS=1 libclntsh.so.12.1`.
2. You may need to add the problematic libraries from glibc-based distro (I use Arch Linux in my `frolvlad/alpine-mono`

DISCLAIMER: While I using this image in production for over a year, I do not give any warranty, so you are welcome to hack around and post issues/solutions, but I won't be able to fix all the issues.

**Comment by urban-1** [comment]
Any workaround for this? I have the same issue...

**Comment by frol** [comment]
@urban-1 Unless you provide more info, I cannot help you. Having a reproduction Dockerfile will help greatly.

**Comment by urban-1** [comment]
Hello @frol, 

My question is if anyone managed to run `cx_Oracle` on this image. I have shifted to the official python image for now since I am running out of time (deadlines :().

The problem is that `libclntshcore.so.12.1` is not happy with `libnsl.so.1`. Although `libnsl.so.1` is installed in your image and if someone exports the correct LD_LIBRARY_PATH ldd can find it, it is still complaining about relocating and symbols...

To reproduce it, get oracle `instantclient`, extract it and export `ORACLE_HOME` on a glibc+python enabled image. Then `pip install cx_Oracle`. Until here everything works since it is a runtime issue... do `python -c 'import cx_Oracle'` or `ldd $ORACLE_HOME/libclntshcore.so.12.1` to see the problem.

If I find some time, I can provide a minimal Dockerfile that demos the issue

**Comment by frol** [comment]
@urban-1 Can you give `frolvlad/alpine-miniconda3` (or `frolvlad/alpine-miniconda2`) image a try? It uses glibc and glibc-based Python.

**Comment by yaroslav-shabalin** [comment]
I have managed to build working image with `cx_Oracle` and `Ansible` (11.2.0.4 Oracle client though) based on `frolvlad/alpine-miniconda2` and some inspiration from `philm/ansible_playbook`. Here is my 2 Dockerfiles:

`FROM frolvlad/alpine-miniconda2

RUN conda install -c cshowers ansible

RUN \
  apk --no-cache add \
    openssh-client \
    tini

RUN mkdir /etc/ansible
RUN echo "[local]" >> /etc/ansible/hosts && \
    echo "localhost" >> /etc/ansible/hosts

WORKDIR /ansible/playbooks

ENV ANSIBLE_GATHERING smart
ENV ANSIBLE_HOST_KEY_CHECKING false
ENV ANSIBLE_RETRY_FILES_ENABLED false
ENV ANSIBLE_ROLES_PATH /ansible/playbooks/roles
ENV ANSIBLE_SSH_PIPELINING True
ENV PATH /ansible/bin:$PATH
ENV PYTHONPATH /ansible/lib

ENTRYPOINT ["/sbin/tini", "-g", "--", "ansible-playbook"]`

`FROM sbt/ansible_conda

RUN conda install -c ostrokach aio
RUN conda install oracle-instantclient cx_oracle

RUN \
  apk --no-cache add \
    curl \
    unzip

WORKDIR /ansible/playbooks/library
RUN \
  curl -fsSL https://github.com/oravirt/ansible-oracle-modules/archive/master.zip -o library.zip && \
  unzip -oj library.zip && \
  rm -rf library.zip

WORKDIR /ansible/playbooks
ENTRYPOINT ["/sbin/tini", "-g", "--", "ansible-playbook"]`

**Comment by frol** [comment]
@yaroslav-shabalin Awesome! Thanks for sharing!
