### ISSUE TITLE
value of field `int_curr_symbol' has wrong length

### ISSUE THREAD

**Issue by suifengcnn** [frol/docker-alpine-glibc#15]
hi，while i have tried to build a images from Dockerfile,I got the WARN message.
------
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
(1/4) Installing glibc (2.25-r0)
(2/4) Installing libgcc (6.2.1-r1)
(3/4) Installing glibc-bin (2.25-r0)
(4/4) Installing glibc-i18n (2.25-r0)
Executing glibc-bin-2.25-r0.trigger
OK: 22 MiB in 21 packages
**LC_MONETARY: value of field `int_curr_symbol' has wrong length
No definition for LC_PAPER category found
No definition for LC_NAME category found
No definition for LC_ADDRESS category found
No definition for LC_TELEPHONE category found
No definition for LC_MEASUREMENT category found
No definition for LC_IDENTIFICATION category found**
(1/1) Purging glibc-i18n (2.25-r0)
OK: 12 MiB in 20 packages
----
Successfully built 47dc001ae5a8

**Comment by suifengcnn** [comment]
docker info
Containers: 17
 Running: 10
 Paused: 0
 Stopped: 7
Images: 36
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.702 GiB
Name: harbor
ID: TWIM:PYDO:3FMT:RBMO:AY4Q:S4TF:SE4A:PGOV:BXVB:FNUP:YYVU:OAHT
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://gmjgd2g2.mirror.aliyuncs.com
Live Restore Enabled: false

uname -r
3.10.0-514.6.2.el7.x86_64

**Comment by frol** [comment]
Those are safe to ignore. Do you have any issues due to those warnings?
