### ISSUE TITLE
Update to alpine 3.6?

### ISSUE THREAD

**Issue by ashleysommer** [frol/docker-alpine-glibc#16]
Would be great to see a new version based on Alpine 3.6
https://alpinelinux.org/posts/Alpine-3.6.0-released.html

**Comment by frol** [comment]
@ashleysommer Thank you for the heads up, I will update today! I didn't know that 3.6 got released!

**Comment by ashleysommer** [comment]
Thanks! I was just reading phoronix news and saw it had just been posted.
I think Alpine 3.6 was released only about an hour before I created this issue.
:smiley:

**Comment by frol** [comment]
Well, there is no Alpine:3.6 image yet... https://github.com/gliderlabs/docker-alpine/issues/284

We have to wait.

**Comment by ashleysommer** [comment]
https://github.com/gliderlabs/docker-alpine/pull/285 was merged a few hours ago,
and just now https://github.com/docker-library/official-images/pull/2984 was merged to update the docker official image, and the image on docker-hub is already updated. :trumpet: :tada:

**Comment by frol** [comment]
Updated with https://github.com/frol/docker-alpine-glibc/commit/aa982e9bdbc104f11f17416b919e3fd9e5901bab! The images are already on DockerHub. Good luck! :)
