### ISSUE TITLE
Relink `/usr/lib/libcrypto.so.42' with `/usr/glibc-compat/lib/libc.so.6' for IFUNC symbol `memcmp'

### ISSUE THREAD

**Issue by darkpssngr** [frol/docker-alpine-glibc#19]
I'm getting this error when running my application.

Relink `/usr/lib/libcrypto.so.42' with `/usr/glibc-compat/lib/libc.so.6' for IFUNC symbol `memcmp'

Not sure if installing librdkafka and librdkafka-dev has to do anything with this.
Please help.

**Comment by frol** [comment]
You shouldn't mix glibc-based binaries with musl-libc-based ones. If your app needs any libs, you should bring them from glibc-based distros (e.g. Arch Linux, Debian, etc) instead of installing Alpine Linux packages. Even if Alpine Linux libraries would work, they are not guaranteed to.
