### ISSUE TITLE
Alpine 3.8

### ISSUE THREAD

**Issue by zhangyoufu** [frol/docker-alpine-glibc#20]
https://alpinelinux.org/posts/Alpine-3.8.0-released.html

**Comment by frol** [comment]
I am waiting for the Docker image: https://github.com/docker-library/official-images/pull/4501

**Comment by jenhsun** [comment]
@frol no rush and keep up the good work. Thanks.

**Comment by frol** [comment]
https://github.com/frol/docker-alpine-glibc/commit/a562f7695834ff5223c1bcd75459e0288fbcbc89
