### ISSUE TITLE
some quirks to make glibc work side by side with musl libc

### ISSUE THREAD

**Issue by MattZhao** [frol/docker-alpine-glibc#26]
Thank you for sharing your image! I am trying to install glibc on Alpine. Could you elaborate a bit on the quirks you applied? I followed instructionn at https://github.com/sgerrand/alpine-pkg-glibc and based on your dockerfile, it seems you are just installing glibc, glibc-bin and glibc-i18n package from the same repo. My image works ok so far but I'm new to building images so just want to make sure I'm not missing anything, and my image built from sgerrand's instruction won't give me any issues in the future.

**Comment by frol** [comment]
There is no tricks, you can see all the instructions necessary to build the image in my Dockerfile.

Why do you need to build the image from scratch (this image has been pulled over 250k times and also used as a base for other images, which are pulled over 2M times, so it is stable and battle-tested)? If you need control over the changes, you can just fork this repo.
