### ISSUE TITLE
Alpine 3.9 is out

### ISSUE THREAD

**Issue by nikolay** [frol/docker-alpine-glibc#28]

**Comment by frol** [comment]
I’m waiting for the alpine:3.9 image: https://github.com/gliderlabs/docker-alpine/issues/480

**Comment by nikolay** [comment]
@frol Why do you care about Gliderlabs's version, when you're using the [official](https://hub.docker.com/_/alpine) one, which already has v3.9?

**Comment by frol** [comment]
@nikolay well, it hasn't been there and Gliderlabs used to release their images earlier than the official one. I will migrate all my images to alpine:3.9 over the weekend. Thanks for the heads up!

**Comment by nikolay** [comment]
@frol Thanks!

**Comment by frol** [comment]
Here you go https://github.com/frol/docker-alpine-glibc/commit/22d4695501ae337a1cf4595c65680e0d1002e0c9

Have fun!

**Comment by nikolay** [comment]
Thank you!

**Comment by nikolay** [comment]
@frol You're missing a tag with both Alpine's and glibc's version numbers.

**Comment by frol** [comment]
@nikolay Good catch. I have just added `alpine-3.9_glibc-2.28` tag.
