### ISSUE TITLE
Alpine Linux 3.10.1 is out

### ISSUE THREAD

**Issue by nikolay** [frol/docker-alpine-glibc#33]
Please, release a compatible image! Not sure why 3.9 is newer than 3.10 and that there's no glibc version in the tag.

**Comment by frol** [comment]
`alpine-3.10_glibc-2.29` is now available (for some reason, Docker Hub hadn't built this tag even though it was configured there a month ago when I migrated to Alpine 3.10).

NOTE: There are only 3.x releases on Docker Hub, so there is no Alpine 3.10.1, it just gets updated on the 3.10 tag if needed.
